name: INPUT 

permissions: 
    contents: read

on: 
    workflow_dispatch:
        inputs: 
            prenom: 
                description: "Ton prenom" 
                required: true 
                type: string    
            age: 
                description: "Ton age"
                required: true 
                type: number
jobs: 
    test: 
        runs-on: ubuntu-24.04
        steps: 
            - name: Dire bonjour
              run: echo "Bonjour \${{ inputs.prenom }}, tu as ${{ inputs.age}} ans !"
