name: TEST VARIABLE ENV

on: 
  workflow_dispatch:

env:
  GLOBAL: "workflow"

jobs: 

  test:
    runs-on: ubuntu-24.04
    steps:

      - name: Récuperer le code 
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        
      - name: caculer la version 
        id: version
        run: | 
            VERSION=$(cat version.txt)
            echo "value=$VERSION" >> $GITHUB_OUTPUT
            echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Afficher les versions 
        run: | 
            echo "Version: ${{ steps.version.outputs.value }}"
            echo "SHA short: ${{ steps.version.outputs.sha_short }}"

  build:
    runs-on: ubuntu-24.04
    env: 
      JOB: "JOB"
    steps: 
      - name: Afficher var d'env 
        env: 
          STEP: "STEP"
        run: | 
            echo "NIVEAU du workflow : ${{ env.GLOBAL }}" # ou $GLOBAL
            echo "NIVEAU du job : ${{ env.JOB }}" # ou $JOB
            echo "NIVEAU du step : ${{ env.STEP }}" # ou $STEP