name: TEST VARIABLE ENV

on: 
  workflow_dispatch:

env:
  GLOBAL: "workflow"

jobs: 
  build:
    runs-on: ubuntu-24.04
    env: 
      JOB: "JOB"
    steps: 
      - name: Afficher var d'env 
        env: 
          STEP: "STEP"
        run: | 
            echo "NIVEAU du workflow : ${{ env.GLOBAL }}"
            echo "NIVEAU du job : ${{ env.JOB }}"
            echo "NIVEAU du step : ${{ env.STEP }}"